### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-translations#10]
I want to request for adding Chinese translation for Qiskit documentations. Meanwhile, I will look for contributors to join the efforts.

**Comment by wangjunchao** [comment]
> I want to request for adding Chinese translation for Qiskit documentations. Meanwhile, I will look for contributors to join the efforts.

Hi,

I want to do the same thing and I have already done some translations.

**Comment by wslu42** [comment]
Hi, I would like to help on the translation as well. Please kindly suggest how to proceed. Thanks!

**Comment by veenaiyuri** [comment]
Hi! Thank you @wslu42! The localization project team is currently going through transition and we are creating a new set of guidelines and criteria for adding new language.  We are planning to reopen translation efforts in July so will let you know how to proceed when ready.

**Comment by wslu42** [comment]
Hey Yuri thank you for replying! I am looking forward to it :) I'm new to open source software and it's awesome to see so many contributors behind this big project!

**Comment by dr-data** [comment]
Hi all. I would like to help with the translation of the traditional Chinese. My name is Dr. Data Ng

**Comment by lebinyu** [comment]
Hi all, I would like to contribute to the translating project. My name is Lebin YU.

**Comment by lebinyu** [comment]
I found someone has done a lot of work translating Qiskit textbook into simplified Chinese.
[https://github.com/xushengun/LearnQuantumComputationUsingQiskit_CN](url)

**Comment by xushengun** [comment]
Let's do it !

Xushengun
18616020096
45045590@qq.com

**Comment by SooluThomas** [comment]
Simplified Chinese has been opened in Crowdin 🎉. Please follow the [instructions in the README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the efforts. Thank you.

**Comment by HuangJunye** [comment]
@SooluThomas Thanks Soolu! I am really excited that Chinese translation is finally happening! For anyone interested in joining the effort, I created a channel for collaboration. Please DM me (@ Junye) on [Qiskit Slack](https://ibm.co/joinqiskitslack).
