### ISSUE TITLE
Slack invite link Error

### ISSUE THREAD

**Issue by minwook-shin** [qiskit-community/qiskit-translations#1114]
### in Readme
```text
For questions regarding onboarding or strategy, to connect with other translators and receive updates regarding the project please join #qiskit-localization channel in the [Qiskit workspace](http://ibm.co/joinqiskitslack) or make an issue in this repo.
```
This Slack [Qiskit workspace](http://ibm.co/joinqiskitslack) invite link is no longer active status.

**Comment by SooluThomas** [comment]
@minwook-shin Can you please check again? Please feel free to reopen if the link is still not working for you. Thanks for reporting

**Comment by minwook-shin** [comment]
@SooluThomas now successfully signed up for the workspace! thanks for refreshing the invite link 😄
