### ISSUE TITLE
Request for Telugu Language

### ISSUE THREAD

**Issue by GayatriVadaparty** [qiskit-community/qiskit-translations#1117]
### Summary

- The language that I'd like to request is Telugu.
- I'd like to be a _Translation Lead_

**Comment by RishiKoushik** [comment]
Hey   @GayatriVadaparty , I am interested to join this translation.
I would love to be a translator.

**Comment by suryadesu** [comment]
Hi @GayatriVadaparty, thanks for raising a request for this. I believe that this helps the community and I love to be part of it like others. I can contribute as a translator and also assist you as a co-translation lead. 

Looking forward to it.

**Comment by mvsg2** [comment]
I am interested in participating in with the translating team as well! :)

**Comment by Jsmka** [comment]
Greetings, @GayatriVadaparty. I am extremely interested in joining your translation endeavor. I would like to contribute both as a **translator** and as a **proof-reader**. It is worth mentioning that I am a **Qiskit Advocate**, which provides me with valuable experience that I believe will greatly benefit this undertaking.

**Comment by SooluThomas** [comment]
Hi all, Thank you for your interest to contribute. Once the team is formed, please follow step 4 in the [instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language)
> 4. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact [Soolu Thomas](mailto:soolu.thomas@ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) and [Yuri Kobayashi](mailto:yurik@jp.ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) by email containing the issue number (or link) and, a little intro about the TL(s) and the team after the above three criteria are met.

**Comment by GayatriVadaparty** [comment]
@SooluThomas Yeah sure, thanks. Will send you all the details about this translation request.

**Comment by nandakishore1807** [comment]
Hi 
I am interested  and would like to contribute as  translator
