### ISSUE TITLE
Incorrect name in contributors and translation lead (Spanish, Spain)

### ISSUE THREAD

**Issue by Arturacu** [qiskit-community/qiskit-translations#114]
I have checked the Translation Lead table from the readme file and the LOCALIZATION_CONTRIBUTORS file and they have incorrectly set a contributor. 

One of the Translation Lead of the Spanish Language is not Antonio Acuaviva Huertos but Arturo Acuaviva Huertos. Antonio Acuaviva Huertos is a translator from the Spanish-Spain (ES) group. 

On the other hand, on the LOCALIZATION_CONTRIBUTORS looks like the name of Arturo Acuaviva Huertos appears just on the Spanish-Mexico (ES-ME) but actually it should appear on both the Spanish-Mexico (ES-ME) and Spanish-Spain (ES).

**Comment by SooluThomas** [comment]
Hi @Arturacu, thank you for pointing out the typo. Can you please confirm your username in Crowdin?

**Comment by Arturacu** [comment]
My username in Crowdin is [arturoacuaviva ](https://crowdin.com/profile/arturoacuaviva)

**Comment by SooluThomas** [comment]
Thank you! PR #115 adds fixes to this issue.
