### ISSUE TITLE
enable PT-PT translation in crowdin

### ISSUE THREAD

**Issue by omarcostahamido** [qiskit-community/qiskit-translations#14]
following on @SooluThomas ' instructions [here](https://github.com/Qiskit/qiskit/pull/552#issuecomment-530136158)

## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

- What is the current text that needs to be fixed or removed? (You can copy and paste)

- What should the documentation say instead?

- Are there other related issues or pull requests about this bug?

## Does existing documentation need to be updated with new content?

- Which files need to be updated?
https://crowdin.com/project/qiskit-docs?
- What content needs to be updated or replaced? (You can copy and paste)
currently there is only option to contribute to JA.
- What new content needs to be added?
support for translation to PT-PT

**Comment by wbillings** [comment]
This issue is tagged as "Language Opened in Crowdin" but I only see PT-BR on the Crowdin project website. Are current efforts only being directed there or is PT-PT also available for help?

**Comment by omarcostahamido** [comment]
Hi @wbillings
This is a very old issue. PT-PT was opened and I worked on it.
Right now both PT-BR and PT-PT are being merged into one.
Hope that helps. 
Question: are you interested in joining the team to translate in PT-PT?

**Comment by wbillings** [comment]
Thanks @omarcostahamido. I am able to help with either, but would prefer PT-PT if it is active. Otherwise I am happy to contribute to PT-BR - just wanted to see what the state of things was before making my PR under one or the other.

**Comment by omarcostahamido** [comment]
@wbillings If you are native PT-PT speaker please do join the PT-PT team.
Even though we are merging both PT-BR and PT-PT, we want to keep track of the translators that are PT-PT and PT-BR.
You can see the teams [here](https://github.com/qiskit-community/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS).

**Comment by omarcostahamido** [comment]
Haha, thx Soolu 😅
