### ISSUE TITLE
Request for Bengali

### ISSUE THREAD

**Issue by amitracal** [qiskit-community/qiskit-translations#147]
### Summary

- The language that I'd like to request.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_
The language that I'd like to request is Bengali. I'd like to be a translation lead for Bengali. We already got at least 3 members - Amitava Chakraborty, Diptiman Dasgupta and myself Abhijit Mitra who are all fluent in Bengali and ready to be part of this project. 
Bengali is the 5th most spoken language in the world spoken by 228 million people. Among the speakers almost two thirds are in the country of Bangladesh and they do a lot of their study in Bengali itself but overall the community has interest in science and Quantum area both in the Bengali speaking part of India (Kolkata) and Bangladesh (Dhaka).

https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

**Comment by veenaiyuri** [comment]
HI @amitracal, please create a pull request (PR) to add your name to the localization contributors list so we can initiate the process. Each member on your team needs to add their names themselves to this list. Thanks.  https://github.com/qiskit-community/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS

**Comment by SooluThomas** [comment]
@abhik-99 Please use this issue for discussion. Thank you!

**Comment by abhik-99** [comment]
As mentioned in #197, our Team consists of @mojutijatir (Quantum Computing Research Fellow at ISI, Kolkata), @thecrazyphysicist369 , @JanapriyoJp, @Aniket049, myself and @aishwarya25252. We have created a Github Org Qiskit-Bangla for everyone interested in this to collaborate on. PR #198 is me adding my name to the list of contributors. Others from our team would follow soon.

We would love it if we could work on this together as a merged team. The more the merrier.

**Comment by ssangskriti** [comment]
Correction: Please edit 'Dhakka' to 'Dhaka'. @amitracal

**Comment by amitracal** [comment]
I do not see where I mentioned 'Dhakka', can you point me in the right
direction?

**Comment by ssangskriti** [comment]
@amitracal in the last line please :) 
![image](https://user-images.githubusercontent.com/25927148/92562588-07eaca80-f298-11ea-9f2b-f35c4bc0c526.png)

**Comment by amitracal** [comment]
Hi,

Sorry for the unintentional spelling mistake. It is corrected now.

Thanks,
Abhijit

**Comment by ssangskriti** [comment]
That's fine! Thanks.
