### ISSUE TITLE
Add Link to "staging website" in Github's repo README.md file

### ISSUE THREAD

**Issue by diemilio** [qiskit-community/qiskit-translations#155]
Hello,

Would it be possible to add the link to the translation [staging website](https://qiskit-community.github.io/qiskit-translations/) to the repo's [README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md) file?

I think the link is only available to translators via the Slack channel, making it difficult for new people to find. I think we would all benefit from having it somewhere where it is readily available with perhaps a short explanation of what what the "staging site" is for (help translators see the content in its final form), and how often it gets updated.

Thanks!

**Comment by SooluThomas** [comment]
Yes, I can definitely add the link. Great suggestion! Thank you
