### ISSUE TITLE
Add links to the respective github profile of our Translation Leads.

### ISSUE THREAD

**Issue by zodiacfireworks** [qiskit-community/qiskit-translations#157]
For a better reach out i think it would be great to add the links to the respective github profile of our Translation Leads. This will make easier for newcommers to reach them out for general questions, review requests or any other volunteer tasks.

**Comment by SooluThomas** [comment]
Thank you, this is a great suggestion. I will add the links.

**Comment by SooluThomas** [comment]
I have added slack usernames instead.
