### ISSUE TITLE
Add Rafael Fister to German translation group

### ISSUE THREAD

**Issue by rafaa95** [qiskit-community/qiskit-translations#170]
Hi I would like to join the German translation group.
Thank you!

**Comment by SooluThomas** [comment]
Hi @rafaa95! Thank you for your interest to contribute, please read the [Guidelines](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to how to sign up to participate in translations. We already have German translations open in Crowdin (#13). Please reach out to the Translation Lead, [Joachim Schaefer](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#translation-leads-as-of-aug-2020). I'm closing this issue. Please use issue #13 for follow-ups. Thank you.
