### ISSUE TITLE
Request for French

### ISSUE THREAD

**Issue by robertxdw** [qiskit-community/qiskit-translations#18]
### Summary

- The language that I'd like to request : French
- I'd like to be a _Translation Lead/ Translator_

**Comment by SooluThomas** [comment]
I just noticed your issue opened in Qiskit repository - https://github.com/Qiskit/qiskit/issues/849. 
> I'm an IBM Quantum Ambassador and preparing Qiskit Advocate Certificat. there are eight of us, all IBMers and we would like to start translate Qiskit in French. I would like to be the translation lead and a translator at the same time. At least one of us will be proofreader. May you add French Language please ?
Thanks

Thanks for your interest in supporting this effort. 😊 

Can all the interested volunteers, who'd like to join, comment here in this issue (mention the role that they'd like to take) and also make a PR for adding their names to the [LOCALIZATION_CONTRIBUTORS](https://github.com/Qiskit/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS) file. Each contributor should add only their own name to the list.

**Comment by robertxdw** [comment]
Ok, we will be launching a Kick-off meeting in the coming days

**Comment by jmit34** [comment]
Hello, I would like to join with robertxdw and team, as translator

**Comment by sylvainp34** [comment]
Hello, I would like to join too as translator. thanks

**Comment by AlainDarmon** [comment]
Hello, I would like to join with team, as translator

**Comment by r0cketr1kky** [comment]
Hello people, I would like to extend my hand in this too @robertxdw

**Comment by SooluThomas** [comment]
French translation is now open in Crowdin 🎉 You can request to join the translations. For more info follow the steps 4 and 5 in the [documentation](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation):

> 4. In the [Qiskit-Docs](https://crowdin.com/project/qiskit-docs) Crowdin project, choose the language that you want to contribute to.
> 5. Click the Join button and paste the URL of your PR in the dialog box where you are asked why you want to join the Crowdin project.
