### ISSUE TITLE
Request for adding language: Traditional Chinese

### ISSUE THREAD

**Issue by dr-data** [qiskit-community/qiskit-translations#196]
### Summary

- The language that I'd like to request: Traditional Chinese
- I'd like to be a _Translation Lead_ and  _Translator_

**Comment by SooluThomas** [comment]
Hi @dr-data! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more people who are interested in doing Urdu translations.

**Comment by akamayu-ouo** [comment]
Hi! 
I'm interested in doing Traditional Chinese translations.

**Comment by dr-data** [comment]
I am from Hong Kong and I am still interested in helping the traditional chinese translation.

**Comment by alanspace** [comment]
I am in Hog Kong, please count me in.

**Comment by wslu42** [comment]
I'm from Taiwan and I'm interested as well. :)

**Comment by starktech23** [comment]
Hi everyone, thanks for your interest! :) It seems we have enough people to open the language, so let's setup a meeting with everyone here if you all are ready to join the project, from there we can discuss roles and onboarding. Please email me at samanvay.sharma1@ibm.com

**Comment by lebinyu** [comment]
I would also like to contribute.

**Comment by HaleyLin2006** [comment]
I'd also liked to be a part of the contributor team!

**Comment by mingweii** [comment]
I'm from Taiwan and interested in comtributing, too!

**Comment by leo07010** [comment]
I would also like to contribute.I am a student from Taiwan

**Comment by qiaoyi213** [comment]
I would also like to contribute. I am a Student from Taiwan!

**Comment by HSUYUCHAO** [comment]
I also want to contribute. I am a student from Taiwan

**Comment by SooluThomas** [comment]
Traditional Chinese has been opened in Crowdin 🎉. Please follow the [instructions in the README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the efforts. Thank you.

**Comment by HuangJunye** [comment]
We am really excited that Chinese translation is finally happening! For anyone interested in joining the effort, I created a channel for collaboration. Please DM me (@ Junye) on Qiskit Slack.

**Comment by Jodie555** [comment]
Hi! I would like to contribute to the translation of Traditional Chinese .
