### ISSUE TITLE
Request for Romanian Language

### ISSUE THREAD

**Issue by BiancaNecula** [qiskit-community/qiskit-translations#199]
### Summary

- The language that I'd like to request is Romanian.
- I'd like to be a Translation Lead and I'm looking for more contributors.

**Comment by SooluThomas** [comment]
Hi @BiancaNecula! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more people who are interested in doing Urdu translations.

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Romanian translations and the issue has been idle for over a year, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
