### ISSUE TITLE
Translation Polish

### ISSUE THREAD

**Issue by pbworker** [qiskit-community/qiskit-translations#23]
Hi - we have a team who can help with polish

Polish local Technical Ambassador.

**Comment by SooluThomas** [comment]
Thanks for your interest in supporting this effort. 😊 

Can all the interested volunteers, who'd like to join, comment here in this issue (mention the role that they'd like to take) and also make a PR for adding their names to the [LOCALIZATION_CONTRIBUTORS](https://github.com/Qiskit/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS) file. **Each contributor should add only their own name to the list.**
