### ISSUE TITLE
 Request for Gujarati Language

### ISSUE THREAD

**Issue by Hirmay** [qiskit-community/qiskit-translations#230]
### Summary

- The language that I'd like to request.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_

**Comment by SooluThomas** [comment]
Hi @Hirmay! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more people who are interested in doing Urdu translations.

**Comment by suraniakbar** [comment]
Hi! I'd also like to be a translator, translator lead or a proofreader. I guess now we just need one more contributor.

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Burmese translations and the issue has been idle for over a year, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
