### ISSUE TITLE
New Leader for the Spanish Mexico Translation

### ISSUE THREAD

**Issue by sita158** [qiskit-community/qiskit-translations#28]
Hi, 

I am leaving IBM today, and I plan to continue as part of this team for the Qiskit docs translation to Spanish, but a new leader will be required for the team.

Thank you...
Vanessa H.

**Comment by derivation** [comment]
Vanessa,
 
Thank you for letting everyone know. Best of luck in your new role beyond IBM.
 
Paul Kassebaum
Content Director
IBM Quantum
paul.kassebaum@ibm.com
M: +1 (508) 981-9735
 
 
----- Original message -----From: sita158 <notifications@github.com>To: Qiskit/qiskit-translations <qiskit-translations@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] [Qiskit/qiskit-translations] New Leader for the Spanish Mexico Translation (#28)Date: Fri, Apr 3, 2020 5:05 PM 
 
Hi,
I am leaving IBM today, and I plan to continue as part of this team for the Qiskit docs translation to Spanish, but a new leader will be required for the team.
Thank you...Vanessa H.

**Comment by carlolsbc** [comment]
Hi,

I want to start contributing to Qiskit, and I think translating might be a good start. After reading Vanessa's message I was wondering what are the needed requirements to be a translation leader.

I am able to do English-Spanish (Mexican) translations, I'm currently working at IBM in Guadalajara.

**Comment by derivation** [comment]
Hi @carlolsbc please email me at paul.kassebaum@ibm.com to discuss.
