### ISSUE TITLE
Request for Urdu

### ISSUE THREAD

**Issue by alihussainia** [qiskit-community/qiskit-translations#286]
### Summary

- The language that I'd like to request is Urdu.
- I'd like to be a Translation Lead.
- The 11th most widely spoken language in the world, with 170 million.
- Good no. of people in technology industry.
- Official Language of Pakistan, the 5th world's largest nation by population.

**Comment by SooluThomas** [comment]
Hi @alihussainia! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more people who are interested in doing Urdu translations.

**Comment by shahtajnazmeen** [comment]
Related  #286

**Comment by alihussainia** [comment]
Greetings, @SooluThomas. 

Now I have 3 translators for Urdu Language, including myself. Kindly, accept the PR now and start the language. :) 

Thank once again, for your time and consideration.I look forward to have a positive and prompt response from your side.

Best Regards,

Muhammad Ali

**Comment by alihussainia** [comment]
Greetings, @veenaiyuri and @SooluThomas , 

It has been 4 days and no one has responded yet. Kindly, look into this matter and accept the PR as 3 contributors have already shown their interest in joining the project and working towards translation (including me). 

I look forward to have a positive and prompt response from your side.

Best Regards,

Muhammad Ali

**Comment by SooluThomas** [comment]
@alihussainia Yes, we are looking into finding a translation lead who is ideally an IBMer. Please send an email to Yuri Kobayashi (yurik@jp.ibm.com) as mentioned in the [README.md ("What is the criteria for adding a new language?")](https://github.com/qiskit-community/qiskit-translations#what-is-the-criteria-for-adding-a-new-language) so that we can collaborate and open the translations accordingly.

**Comment by alihussainia** [comment]
@SooluThomas Thank you for responding amiga, yes have already sent an email but have not received the feedback. I proposed that I wanted to become a Translation Lead. If you can forward the request to Yuri, I will be really grateful to you. :)

**Comment by alihussainia** [comment]
The email I sent the request from is : malirashid1994@gmail.com

**Comment by SooluThomas** [comment]
Urdu translations are now open in Crowdin! 🎉

**Comment by SooluThomas** [comment]
Closed this issue due to inactivity
