### ISSUE TITLE
Request for KOREAN

### ISSUE THREAD

**Issue by keeseon** [qiskit-community/qiskit-translations#30]
### Summary

- The language that I'd like to request. - Korean
- I'd like to be a _ Translator_

**Comment by SooluThomas** [comment]
Hi @keeseon, We already have Korean open in Crowdin. So please go ahead and open a PULL REQUEST in this repository to add your name to the LOCALIZATION_CONTRIBUTORS file, sign the CLA (will pop up in your PR) and send a request to Qiskit-Docs crowdin project along with the link to your pull request as mentioned in the [documentation](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation)

**Comment by SooluThomas** [comment]
Duplicate Issue #5
