### ISSUE TITLE
Request for Arabic

### ISSUE THREAD

**Issue by lamiaehana** [qiskit-community/qiskit-translations#300]
**Summary**
The language that I'd like to request is Arabic.
I'd like to be a Translation Lead.
Arabic is spoken by 422 million speakers
Good no. of people in technology industry.
Official Language of 25 countries.

**Comment by SooluThomas** [comment]
Hi @lamiaehana! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Arabic translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).

**Comment by Rayyan10** [comment]
Hi there! I'm interested in contributing as a translator and/or a proofreader.

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Arabic translations and the issue has been idle for over a year, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.

**Comment by Rayyan10** [comment]
Hi @lamiaehana  ! Hope you’re doing well 
I have opened an issue and requested for Arabic translation. If you are still interested in contributing please comment on [Request for ARABIC ](https://github.com/qiskit-community/qiskit-translations/issues/959) as we need more contributors.
Thank you!
