### ISSUE TITLE
Please create Greek language for qiskit translation

### ISSUE THREAD

**Issue by vasiliskat** [qiskit-community/qiskit-translations#35]
Dear Sir/Madam,

I have undertaken to translate qiskit in Greek language. Please create the new request.

Thank you

**Comment by SooluThomas** [comment]
Hi @vasiliskat, due to transition in the supporting team, no new languages will be added to the documentation. However, please continue to recruit translation team members here in this issue. Everybody interested to volunteer for Greek translations can comment here along with the role (Team Lead, Translator, Proofreader) they'd like to take. See [documentation](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) for more information. Thanks for your interest! 😊

**Comment by vasiliskat** [comment]
@SooluThomas Thank you for your answer. I will wait until the transition finishes. In parallel, I will start the translation working locally on my laptop. Do you know on which texts should I focused on? I will be translator and team leader for Greek language. Furthermore, I tried to open a pull request also, but the button is disabled. I have also signed the CLA.

**Comment by SooluThomas** [comment]
@vasiliskat I'm very happy to see your interest. But before the translation is open, there must be enough volunteers to contribute to the same (including translation lead, proofreaders, translators).  So if anyone you know is interested in volunteering they can use this issue to tell what role they'd like to take.

**Comment by vasiliskat** [comment]
@SooluThomas I reopened PR #34 as you mentioned and waiting for review

**Comment by SooluThomas** [comment]
@vasiliskat We need to meet some [criteria](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language) before creating a new language in Crowdin.
>1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
>2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by vasiliskat** [comment]
@SooluThomas I have found two other contributors, so we will cover the required number to start the translation in Greek language. They will proceed with PR and CLA in the next days.

**Comment by SooluThomas** [comment]
@vasiliskat Please ask them to comment here and open a PR as well. Also, follow the above mentioned step 3 (send an email to Yuri Kobayashi). Thank you.

**Comment by akoustef** [comment]
@SooluThomas Hi, i will be contributing in the project

**Comment by vmoulos** [comment]
@vasiliskat, I am also on board.

**Comment by phanouriou** [comment]
Hi, I am also contributing to the project.

**Comment by vasiliskat** [comment]
@SooluThomas We have the necessary number of contributors to create Greek language in crowdin. What's next?

@phanouriou @vmoulos @akoustef please follow the steps as presented in the below link and sign the CLA

https://github.com/qiskit-community/qiskit-translations

**Comment by SooluThomas** [comment]
@vasiliskat Please follow the above mentioned [step 3 of adding new languages section](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language) (send an email to Yuri Kobayashi). Thank you.
>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by SooluThomas** [comment]
@akoustef @vmoulos @phanouriou We have opened Greek in Crowdin. Feel free to follow the [onboarding steps](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) and send joining request in Crowdin. 

Please comment below If you have any difficulties in opening a Pull Request.
