### ISSUE TITLE
Request for Tamil Language

### ISSUE THREAD

**Issue by ManjulaGandhi** [qiskit-community/qiskit-translations#353]
### Summary
I am a Qiskit Advocate and would like to be part of translating Qiskit Texbook in Tamil Language.
I would like to take the role of Translation Lead.
Requesting all those who are interested in my community to join as well.

**Comment by SooluThomas** [comment]
Hi @ManjulaGandhi! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader as mentioned in the [instructions](https://github.com/qiskit-community/qiskit-translations#what-is-the-criteria-for-adding-a-new-language). Let us use this issue to recruit more people who are interested in doing Tamil translations.

**Comment by Nandanaa** [comment]
Hi @ManjulaGandhi Ma'am! I am interested to contribute as a translator for QisKit. Thank You!

**Comment by Nithyanantham-cyber** [comment]
Hello @ManjulaGandhi Ma'am, I wanted to be in part of translation of Qiskit book to tamil as a translator. Thank you!!

**Comment by sgayathridevi** [comment]
Hi @ManjulaGandhi mam, I am from India! I would like to be part of this translation work. I want to take a role of Proof Reader!

**Comment by chandia79** [comment]
Hi @ManjulaGandhi mam, I am from India. I would like to be a Proof Reader.
Thank You

**Comment by RagavBoobal** [comment]
Hello @ManjulaGandhi  Mam, I am Interested to work as a translator for qiskit. Thank You Mam!!!!

**Comment by Ashwin1950** [comment]
Hi @ManjulaGandhi Ma'am! I am interested to contribute as a translator for QisKit. Thank You!

**Comment by ReshmaDhandapani** [comment]
Hello @ManjulaGandhi Mam, I am Interested to work as a translator for qiskit. Thank You Mam...

**Comment by VaniKH** [comment]
Hello @ManjulaGandhi mam,I would like to be a  part of translation work,I would like to be a proofreader.Thank you mam

**Comment by sathyachinnathambi** [comment]
Hai @ManjulaGandhi mam, I would like to be a part of  tamil translation work, I would like to be a proofreader. Thank you mam

**Comment by SooluThomas** [comment]
Since I see quite a lot of number of interested contributors, @ManjulaGandhi Please send an email to yurik@jp.ibm.com cc: samanvay.sharma1@ibm.com and we can get started from there.

**Comment by ManjulaGandhi** [comment]
Sure @SooluThomas . Thanks a lot.

**Comment by RajeshJeyapaul** [comment]
Hello @ManjulaGandhi , as discussed , I am interested to be part of this translation work. I am an certified IBM Quantum Ambassador.I can do the proof reading.Thx

**Comment by snekithasri** [comment]
Hello @ManjulaGandhi Mam, I am Interested to work as a translator for qiskit. Thank You Mam!

**Comment by SooluThomas** [comment]
We have enabled Tamil translations in Crowdin and the team lead is @ManjulaGandhi. Please go ahead and follow the [steps to join the translation team](https://github.com/qiskit-community/qiskit-translations#to-sign-up-to-participate-in-translations) and also the #tamil channel in Qiskit-docs slack workspace. Click on the link to join the workspace  - http://bit.ly/qiskitdoc

**Comment by sgayathridevi212** [comment]
I wish to be a Proof Reader..

**Comment by Pratheeksha191** [comment]
Hello @ManjulaGandhi Mam, I am Interested to work as a translator for Qiskit. Thank You Mam!

**Comment by Pratheeksha191** [comment]
Hello @ManjulaGandhi Mam, I am Interested to work as a translator for qiskit. Thank You Mam.
