### ISSUE TITLE
Request for Vietnamese

### ISSUE THREAD

**Issue by RossyNguyen** [qiskit-community/qiskit-translations#358]
### Summary

- The language that I'd like to request.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_

**Comment by veenaiyuri** [comment]
Hi @RossyNguyen ! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader as mentioned in the instructions. Let us use this issue to recruit more people who are interested in doing Vietnamese translations.

**Comment by dukeraphaelng** [comment]
Hi, I'd also like to be a Translation Lead/ Proofreader/ Translator for the Vietnamese language

**Comment by RossyNguyen** [comment]
Hi Duke,

Thanks for your interest. Can you give me some more info about yourself
(ie: your base and availability)? I will prepare the onboarding process for
you.

Kind regards,
Rossy Nguyen

**Comment by dukeraphaelng** [comment]
Hi Rossy, could you please provide me with your email?

**Comment by RossyNguyen** [comment]
Of course, here is my email address:
***@***.***

Regards,
Rossy Nguyen

**Comment by dukeraphaelng** [comment]
Sorry for the late reply! I just sent you an email.
