### ISSUE TITLE
Add Hindi Language

### ISSUE THREAD

**Issue by r0cketr1kky** [qiskit-community/qiskit-translations#4]
Is it possible to add Hindi too?
https://crowdin.com/project/qiskit-docs

I would love to volunteer as the translation lead. 
I would love to have more volunteers pitch in to help me.

**Comment by SooluThomas** [comment]
@born-2learn Please follow-up here.

**Comment by born-2learn** [comment]
Following up from #162 
I am interested to work as a _Translation Lead/Translator_ for the new language Hindi(HI)

**Comment by rawatraghav** [comment]
I am interested in contributing to Translation for the new language Hindi(HI)

**Comment by r0cketr1kky** [comment]
@SooluThomas I think we can fire this issue up now. But I guess we could probably wait for 1-2 more volunteers to pitch in.

**Comment by SooluThomas** [comment]
>- We want to translate the Qiskit textbook and documentation to Hindi. (Hindi is the lingua franca for over 500 million people and there is a huge growing interest in Quantum among Indian Students. We observed some students already working on Qiskit but we are aiming for better outreach via India Quantum Challenge, Professor Collaborations and several other mediums.)
>- I'd like to be a HINDI_Translation Lead. I am a native Hindi speaker and I am the lead researcher for Watson NLP stack extension to Hindi. I have Quantum theory knowledge and Qiskit understanding. I am taking the Qiskit Advocate test and also lined up for my Quantum Ambassador training in September
I have a team of people in IBM Research India and some from IBM India (Systems and Quantum Computing COC) with whom we are trying to create the India Ecosystem. There are 4 Q-Ambassadors out of which one will be the proofreader and others will join for translation like me.

@anupamaray

**Comment by SooluThomas** [comment]
@r0cketr1kky, We'll be having a meeting with Anupama (@anupamaray) tomorrow and will soon open Hindi in Crowdin. Please open a pull request to edit the [LOCALIZATION_CONTRIBUTORS](https://github.com/qiskit-community/qiskit-translations/edit/master/LOCALIZATION_CONTRIBUTORS) file by adding "Hindi (HI)" as a new heading with your name under it. Then commit changes. Please make sure to sign the CLA after you have successfully committed changes. 

**Please note that every person has to open a PR to add their names to the file.**

**Comment by r0cketr1kky** [comment]
Done :) 
@SooluThomas

**Comment by hardik-dadhich** [comment]
Hi, @r0cketr1kky I am interested in contributing to Translation for the language Hindi(HI). Can you please let me know if I can?

**Comment by SooluThomas** [comment]
Hi @hardik-dadhich! Thank you for your interest to contribute. We have already started to Hindi translations in Crowdin. You are always welcome to join us by following the [steps in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to sign up for the translations in Crowdin. You could also socialize with the rest of the translation team by joining #hindi channel in the [Qiskit Docs workspace](http://bit.ly/qiskitdoc) as well. Feel free to reach out to the translation lead (listed in the README.md file).
