### ISSUE TITLE
Qiskit in Burmese

### ISSUE THREAD

**Issue by heinzay1999** [qiskit-community/qiskit-translations#40]
Hi! I am from Burma and I am currently studying in America. I was wondering whether translating Qiskit into Burmese would be a good idea to introduce quantum computing into Burma. What do the rest of the GitHub community think ?

**Comment by SooluThomas** [comment]
Hi @heinzay199! Thanks for your interest in contributing to the Qiskit Documentation translations effort. We would want to checkmark the [following criteria](https://github.com/qiskit-community/qiskit-translations#what-is-the-criteria-for-adding-a-new-language) before actually opening Malayalam translations in Crowdin. 

> 1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
> 2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
> 3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project. 

Meanwhile, we could use this issue for more people to volunteer for various roles.

Once again, thank you so much for volunteering to contribute! 🎉

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Burmese translations and the issue has been idle for over a year, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
