### ISSUE TITLE
Request for Kiswahili

### ISSUE THREAD

**Issue by Phystro** [qiskit-community/qiskit-translations#423]
### Summary

- I would like to request for a Swahili translation.
- I'd like to be a _Translation Lead/Translator_

**Comment by thismaker** [comment]
That is a great idea. Myself I would be willing to help if that is okay.

**Comment by Phystro** [comment]
sure @thismaker

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Swahili translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).

**Comment by Ericongeri** [comment]
Hi. I would like to help in translating the content to Swahili also.

**Comment by Ericongeri** [comment]
I can be a translator in the project.😁

**Comment by Phystro** [comment]
Hi, @SooluThomas, I think we can proceed with contributing to the translations seeing as we do have a minimum of three willing contributors.

**Comment by Kokota-17** [comment]
Hi, I would like to help in proofreading Swahili translations

**Comment by Phystro** [comment]
Hi @SooluThomas I sent an email to @veenaiyuri but haven't received any feedback yet.

**Comment by veenaiyuri** [comment]
@Phystro Thank you for your interest in translating the docs into Swahili. I have sent you a response so please check your email. Thank you.

**Comment by SooluThomas** [comment]
We have Swahili opened in Crowdin. Please send your joining requests to Crowdin as per the sign-up instructions in the [README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations)
