### ISSUE TITLE
Request for Slovak language

### ISSUE THREAD

**Issue by MarosRusnak** [qiskit-community/qiskit-translations#477]
### Summary
- The language that I'd like to request.
Slovak

- I'd like to be a Translation Lead/ Proofreader/ Translator
MarosRusnak

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Slovak translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Slovak translations and the issue has been idle for over 6 months, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
