### ISSUE TITLE
Add Korean Language to Localization

### ISSUE THREAD

**Issue by jinho10** [qiskit-community/qiskit-translations#5]
I am a qiskit advocate and would like to start contributing from the documentation. I would like to be a translation lead for my main role (translation experience), but at the same time I also want to perform as Translators and Proofreaders.

I already pull requested to add myself to the LOCALIZATION_CONTRIBUTOR

https://github.com/Qiskit/qiskit/pull/731

I am asking around my Korean community to join as well.

**Comment by veenaiyuri** [comment]
@all-contributors add @jinho10 for translation

**Comment by veenaiyuri** [comment]
@all-contributors add @jinho10 for translation

**Comment by veenaiyuri** [comment]
@all-contributors add @jinho10 for translation
