### ISSUE TITLE
Request for Telugu

### ISSUE THREAD

**Issue by GopikaRao** [qiskit-community/qiskit-translations#503]
### Summary

-  Telugu - The language that I'd like to request.
- I'd like to be a- Translation Lead
- Stats about #Telugu language NATIVE: 70 million 2nd: 5 million TOTAL: 75 million World Rank: 11

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. We are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Slovak translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).

**Comment by SooluThomas** [comment]
@GopikaRao I see that a few PRs opened to add names to the LOCALIZATION_CONTRIBUTORS file where it is clearly evident more than 3 volunteers are interested. Please follow step 3 of [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate)

>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Samanvay Sharma (samanvay.sharma1@ibm.com) and Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by SooluThomas** [comment]
Due to inactivity from @GopikaRao. This issue and all related PRs will be closed. Please reopen if anyone else would like to be the lead for this language. Thank you for your interest to contribute.
