### ISSUE TITLE
Request for Bulgarian language

### ISSUE THREAD

**Issue by vkabadzhova** [qiskit-community/qiskit-translations#541]
### Summary

- The language that I'd like to request is _Bulgarian_
- I'd like to be a _Translation Lead/ Translator_

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. Initially, we are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Bulgarian translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Slovak translations and the issue has been idle for over 3 months, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
