### ISSUE TITLE
Request for Persian

### ISSUE THREAD

**Issue by zaqas** [qiskit-community/qiskit-translations#553]
### Summary

- The language that I'd like to request is Persian (Farsi).
- I'd like to be a _Translation Lead_/_Translator_

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. Initially, we are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Persian translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).
>1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
>2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Samanvay Sharma (samanvay.sharma1@ibm.com) and Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by ali-erpupone** [comment]
Hi, I would like to join as proof reader/translator.

**Comment by SooluThomas** [comment]
Tagging @nema9210 @tantak @ajjahan here.

**Comment by starktech23** [comment]
@zaqas @ali-erpupone @nema9210 @tantak @ajjahan

Hi all, resuming this issue here. If you are still available to contribute to the Qiskit Localization Project by adding Persian as a language, please respond to this comment and take a look at [this README.md section](https://github.com/qiskit-community/qiskit-translations#what-is-the-criteria-for-adding-a-new-language) for next steps; we can set up a discussion space from there. Let me know if you have any questions and thanks again for your interest!

> 1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
> 2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
> 3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact [Soolu Thomas](mailto:soolu.thomas@ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) and [Yuri Kobayashi](mailto:yurik@jp.ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) by email for the language to be officially listed under this project.

**Comment by zaqas** [comment]
@starktech23  I am still interested. Having read the section, I would be interested to act as Translation Lead/Translator. If we are still waiting for other members to join the discussion, I can wait.

**Comment by nema9210** [comment]
Dear ALL,

I would like to contribute as well.

Regards,
Delaram


________________________________

**Comment by ali-erpupone** [comment]
Hey everyone, 

I am glad to see so much enthusiasm around this project. I'm ready and committed to begin working to bring this project into action.  I have also read the section and I am all set.

**Comment by SooluThomas** [comment]
Hi all! If you are still available to contribute to the Qiskit Localization Project by adding Persian as a language, please respond to this comment and take a look at [this README.md section](https://github.com/qiskit-community/qiskit-translations#what-is-the-criteria-for-adding-a-new-language) for next steps; we can set up a discussion space from there. Let me know if you have any questions and thanks again for your interest!

> 1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
> 2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
> 3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact [Soolu Thomas](mailto:soolu.thomas@ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) and [Yuri Kobayashi](mailto:yurik@jp.ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) by email for the language to be officially listed under this project.

**Comment by zaqas** [comment]
@SooluThomas Hey!

We have already responded to the request made by @starktech23 a while ago. We are still waiting to see Persian language to be officially listed under the project. I do not understand why you haven't added the language officially yet, as the translation lead/translator/proof reader have been identified and the minimum number of contributors is met. I have contacted you and Yuri via email and no response was received on my side. Please check your email or provide me with another way of contacting you.

Thanks

**Comment by SooluThomas** [comment]
@zaqas I'm curious if the step 3 in the above comment was satisfied or not.

> 3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact [Soolu Thomas](mailto:soolu.thomas@ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) and [Yuri Kobayashi](mailto:yurik@jp.ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) by email for the language to be officially listed under this project.

Please let me know.

**Comment by zaqas** [comment]
@SooluThomas I am the translation lead and I sent an email few days ago. If you have not received the email, let me know so I can send another email again.

**Comment by SooluThomas** [comment]
@zaqas I don't see any email. Can you please connect over Slack? https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#project-leads or try resending it again?

**Comment by zaqas** [comment]
@SooluThomas I just sent you an email.

**Comment by zaqas** [comment]
I sent an email to the email on your Github profile under the subject: Persian Language (Qiskit)

**Comment by SooluThomas** [comment]
ok, I received the one sent to the GitHub email. I'll forward them to Yuri too. Thanks

**Comment by zaqas** [comment]
@SooluThomas Any update?

**Comment by veenaiyuri** [comment]
@zaqas Thanks for following up on this. Since your team has met the criteria for your language to be added, I will reach out to you separately to have an onboarding meeting. Thanks!

**Comment by nema9210** [comment]
Hello Reza,

Thanks for your email. I was eager to do to the translation, but I do not have much time now. I can do some in the weekends.
Can we have a meeting to figure out what we need to do?

Regards,
Delaram



From: Reza Ghasemi ***@***.***>
Date: Wednesday, June 1, 2022 at 8:29 PM
To: qiskit-community/qiskit-translations ***@***.***>
Cc: Nematollahi, Delaram ***@***.***>, Mention ***@***.***>
Subject: Re: [qiskit-community/qiskit-translations] Request for Persian (#553)

@nema9210<https://urldefense.com/v3/__https:/github.com/nema9210__;!!GNU8KkXDZlD12Q!762QFCm5QudcJHIkqUuxe_6GYskB_LKF0iU0yDYY9rxowVDTlWFZCXdzzv6WRy9tPNDRTGOqJaIbwwlzJB47ODxB-ZeCaWx-IQ$> Hey Delaram, Did you receive my email? If so, can you send me a reply back as soon as you can? Thanks in advance.

**Comment by zaqas** [comment]
@nema9210 Of course! Since you have my email address now, send me a reply back so we can continue our conversation in private. If you prefer other methods of communication (e.g. chatting), please do specify in the email.

**Comment by 0sophy1** [comment]
Hi team Persian- @nema9210 @zaqas @ali-erpupone , we've tried to set up a call and an onboarding meeting with you guys but it seems the communication stopped. Please visit[ Qiskit slack](https://ibm.co/joinqiskitslack) and DM @sophy to continue the discussion.

**Comment by SooluThomas** [comment]
@zaqas, we had scheduled to meet today for an onboarding meeting but didn't get any response from your side. Please note that this is not the first time getting a no-show for a scheduled meeting. It seems like the language team is somewhat inactive at this point and will be move towards closing this issue **soon** due to inactivity.

**Comment by zaqas** [comment]
@0sophy1 @SooluThomas We decided not to collaborate with your team anymore since I had to pressure Yuri to have a meeting each time and everytime she canceled it for some reason and reached out to me and said you had to cancel because you were working on other things. Obviously we have papers to write and present  and we deserve respect instead of last minute cancellation. We were supposed to have onboarding session with Yuri in August but she said it would be in September and then stopped communication (both via email and on slack). If you do want a specific language, just say it before wasting everybody's time. Good luck!

**Comment by SooluThomas** [comment]
@zaqas As per our conversation over slack, it is very clear that as someone who had **volunteered to be a translation lead**, you failed to attend the scheduled meetings and respond to the project leads emails. It is the TL’s responsibility to reach out to the interested members and to be proactive in creating a team, letting the leads know how passionate the team is and responding to emails from project leads. But in this case, we couldn’t see that.

Pasting my slack message here:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/11485594/200135453-f6a4d0fc-fafe-4f72-9412-d3ff80bb178f.png">


Please refrain from making unprofessional comments.

**Comment by zaqas** [comment]
@SooluThomas Obviously you seem to lack experience in this field and do not know how to communicate. I told Yuri that we would have to do the onboarding session before October but you specifically delayed it until October. I even told Yuri that Neema would not contribute and we had another member. But since you do not communicate and lack the management capability as it can be seen by everyone since so many languages have been left to rot, maybe you should work on communication skills before trying to implement Shorr's algorithm ;)

Please stop spamming us since we have moved on to other projects.
