### ISSUE TITLE
Request for Nepali

### ISSUE THREAD

**Issue by ishworii** [qiskit-community/qiskit-translations#556]
### Summary

- The language that I'd like to request is Nepali.
- I'd like to be a  Translation Lead/ Proofreader/ Translator

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. Initially, we are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Nepali translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).
>1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
>2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Samanvay Sharma (samanvay.sharma1@ibm.com) and Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by SooluThomas** [comment]
Thank you for your interest to contribute. Since there hasn't been any volunteers to support Nepali translations and the issue has been idle for over 3 months, I'm gonna close this issue. Feel free to reopen it if more volunteers are willing to contribute.
