### ISSUE TITLE
Request for Marathi

### ISSUE THREAD

**Issue by des137** [qiskit-community/qiskit-translations#580]
### Summary

- The language that I'd like to request is Marathi.
- I'd like to be a _Translation Lead_  and/or a _Proofreader_.

Hopefully this issue can be used for recruiting/finding 2 additional translators for Marathi.

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. Initially, we are looking for a minimum of 3 people to start a new language to fulfill the roles of Translation Lead, translator, and proofreader. Let us use this issue to recruit more volunteers who are interested in doing Marathi translations. 

For more info, please refer to [**How to add a new language to translate?** section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).
>1. A minimum of three contributors is necessary for any new languages to be added and receive official support from the administrators of the localization project.
>2. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language, to ensure the translations can be released in that language.
>3. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact Samanvay Sharma (samanvay.sharma1@ibm.com) and Yuri Kobayashi (yurik@jp.ibm.com) by email for the language to be officially listed under this project.

**Comment by anuragkulkarni** [comment]
I would like to offer my assistance in translation Qiskit documents in marathi

**Comment by bopardikarsoham** [comment]
I would also like to offer a hand in Marathi

**Comment by bopardikarsoham** [comment]
I think we have 3 now @des137 @anuragkulkarni

**Comment by des137** [comment]
Hi @SooluThomas,

Since we now have a group of 3 people, can you please let us all know what the next steps are for Marathi to be officially listed under this project?

**Comment by bopardikarsoham** [comment]
@SooluThomas !

**Comment by bopardikarsoham** [comment]
@SooluThomas!

**Comment by starktech23** [comment]
Hi @bopardikarsoham! As mentioned in the past comment by @SooluThomas, you now have atleast 3 contributors who I assume will be contributing mostly as translators as per the first step. 

[According to the next two steps](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language), we would need you to ask atleast 1-2 dedicated proofreaders to join your team to help maintain the accuracy of the translations and content of the documentation in Marathi.

After this, please identify a Translation Lead to communicate with the project admins, contact us via email (samanvay.sharma1@ibm.com, yurik@jp.ibm.com) and we can set up a meeting from there.

**Comment by Mit-byte** [comment]
I would also like to contribute in translation of Qiskit docs to Marathi.

**Comment by SchrodingersSangru** [comment]
I'd also like to contribute for this..

**Comment by kabir1729** [comment]
I would also like to contribute for translation of docs in Marathi and proofread that

**Comment by SooluThomas** [comment]
@kabir1729 We already have Marathi opened in Crowdin. Please follow [these steps](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the team. Thank you for your interest to contribute
