### ISSUE TITLE
Add Brazilian portuguese language

### ISSUE THREAD

**Issue by gilbion** [qiskit-community/qiskit-translations#6]
Hello,

I would like to have the Qiskit documentation translated from English to Brazilian Portuguese. 

I can participate in the translation project as either the Translation Leader or the Proofreader.

I also have a couple other people that would like to participate in the translation effort.

Thank you!

**Comment by liroberta** [comment]
Hi,

I would like to be added to PT-BR translation as translator.

**Comment by jholiv** [comment]
Hi,

I would like to help with the Brazilian Portuguese translation.

**Comment by venanx** [comment]
Hello ! 

I would like to help with the PT-BR translation.

**Comment by viviurbano** [comment]
Hi,  I would like to be added to PT-BR translation as tradutor. 

Thank you!

**Comment by gbrosa** [comment]
Please, add me. Tks!

**Comment by RonaldoPA** [comment]
I'd like to be added to PT-BR translation as a translator

**Comment by ricardonnn** [comment]
Hi, I would like to be added to PT-BR translation as translator.
Tks!

**Comment by lgaleoti** [comment]
Hello, I would like to be added to PT-BR translation as translator.
Tks!

**Comment by gisellefs** [comment]
Hi,

I would like to help with the Brazilian Portuguese translation.

**Comment by AndressaMerlo** [comment]
I would like to be added to PT-BR translation as **translator**

**Comment by FrancisRicalde** [comment]
Hi, I would like to be added to PT-BR translation as translator.

**Comment by pluciana** [comment]
Hello, I would like to contribute as translator.

**Comment by Claudiasp** [comment]
I would like to be added to PT-BR translation as translator

**Comment by maucb** [comment]
Hello, I would like to be added to PT-BR translation as translator.
Tks!

**Comment by lmtome** [comment]
I would like to be added to PT-BR translation as translator

**Comment by kelson-martins** [comment]
Hello,
I would like to be added to PT-BR translation as translator

**Comment by fabicaminiti** [comment]
Hello, I would like to be added to PT-BR translation as translator.

**Comment by achristinne** [comment]
Hi All,
I am also interest in translating to Brazilian Portuguese . Thanks

**Comment by marcella-santana** [comment]
Hi,
I would like to be added to PT-BR translation as translator. Thanks.
