### ISSUE TITLE
I have added my name to the LOCALIZATION_CONTRIBUTORS file under Russian language.  Related #9

### ISSUE THREAD

**Issue by olgaatgh** [qiskit-community/qiskit-translations#655]

**Comment by SooluThomas** [comment]
So, I took a look at the PR. Looks like you have a different user config in your local. 

Things that you could do:
- Make edits in GitHub itself
   1. Click on the pen like button which says "Edit this file" in [LOCALIZATION_CONTRIBUTORS](https://github.com/qiskit-community/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS) file 
   2. Add your name under the Language you'd like to contribute to
   3. Once your name is added, scroll down and fine the green button which says "Propose changes"
   4. The page now reloads and you can find another green button "Create pull request". Click on that.
   5. This should create the pull request and once that's done, follow the [instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) (step 3, 4, 5) and request to join in [Crowdin](https://crowdin.com/project/qiskit-docs).
- In the CLI:
   1. Create a new branch based off of the master branch 
   2. Edit the LOCALIZATION_CONTRIBUTORS file
   3. Run `git config user.name <your GitHub username>`. Eg.: `git config user.name olgaatgh`
   4. Run `git config user.email <your GitHub registered email>`. Eg.: `git config user.email example@example.com`
   5. Then add, commit, push changes and create pull request.
