### ISSUE TITLE
Request for Persian/Farsi

### ISSUE THREAD

**Issue by nema9210** [qiskit-community/qiskit-translations#681]
### Summary

- The language that I'd like to request.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_
Persian/Farsi 
Delaram Nematollahi

**Comment by tantak** [comment]
Hi, I am Zahra Sadri, and I want to contribute to Farsi translation.

**Comment by tantak** [comment]
I want to contribute to translating in Farsi, how can I sign CLA?

**Comment by ajjahan** [comment]
Hello, I would like to contribute. Please let me know who can I join.

**Comment by ajjahan** [comment]
I can start by translating to Farsi.

**Comment by veenaiyuri** [comment]
Thank you for your interest in joining the Qiskit localization project. This is a duplicate request of issue #553 and add your comment. Thank you!
