### ISSUE TITLE
Add Turkish Language

### ISSUE THREAD

**Issue by Ayshine** [qiskit-community/qiskit-translations#7]
I would like to contrıbute the translation project as Team Lead. 
Would it be possible to add the Turkish language?
https://crowdin.com/project/qiskit-docs

**Comment by fgnyilmaz** [comment]
Hi, this is Figen YILMAZ and have an MSc degree in physics (Quantum Algorithms). Willing to contribute to Turkish localization/translation as a proofreader.

**Comment by cyasar** [comment]
Hi, My name is Cumali Yaşar and have an PHd degree in physics. i want to  to contribute to Turkish localization/translation as a tecnical redactor
