### ISSUE TITLE
Documentation expected as code appearing as quote in Japanese documentation page

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-translations#730]
On this page: https://qiskit.org/documentation/locale/ja/apidoc/execute.html, I believe some part of the documentation should be code and not quotes (which is the form it is currently appearing in).

For example, consider this on the Japanese page:
![image](https://user-images.githubusercontent.com/61590679/131418930-1362ffe1-8dfc-4922-8b18-7fa461581175.png)
(Part of the doc is leaking out of the quote block)

This is how it appears in the English page: https://qiskit.org/documentation/apidoc/execute.html

![image](https://user-images.githubusercontent.com/61590679/131419021-dddd215a-9f92-4dae-a5c4-33bf45c1846c.png)

It appears that the Japanese page is still under development - but it would be good if we could track this in an issue, as this is not related to translation. 

(I do not have knowledge of the Japanese language - maybe @veenaiyuri you would like think over this issue?)

**Comment by SooluThomas** [comment]
@dhruvbhq You are looking at an older documentation. The most recent Japanese docs is under the link - https://qiskit.org/documentation/locale/ja_JP/apidoc/execute.html.

I hope this resolves the issue.
