### ISSUE TITLE
Request for Thai 

### ISSUE THREAD

**Issue by BankNatchapol** [qiskit-community/qiskit-translations#744]
### Summary

- The language that I'd like to request is Thai.
- I'd like to be a Translation Lead.
- I already have a Proofreader and Translator.

**Comment by EPongophas** [comment]
็Hello everyone. My name is Ekkarat Pongophas. I am Thai. I am one of the translation team from Thailand. If you want to contact me, this is my email: e.pongophas@gmail.com.

**Comment by ksupasate** [comment]
Hello everyone. My name is Supasate Vorathammathorn. I'm a computer engineer student at KMUTT from Thailand. If you want to contact me, this's my email: ksupasate@gmail.com

**Comment by EinQU** [comment]
Hello everyone. My name is Ekapong Hirunsirisawat. I am Thai. I am one of the translation team from Thailand. If you want to contact me, this is my email: [ekapong.hirun@gmail.com](mailto:ekapong.hirun@gmail.com).

**Comment by Kachanon** [comment]
Hello, world. My name is Kachanon. My e-mail address is Kachanon@yahoo.co.uk .

**Comment by 0sophy1** [comment]
Hi @BankNatchapol, as Thai already added and well going, can we close this PR? Thanks

**Comment by portunwa** [comment]
Hello everyone, my name is Tunwa Satianrapapong. My nickname is Por. I'm Computer Engineering student at KMUTT and I would like to participate in this translation to explore more about Quantum. 

This is my Email: portunwa@gmail.com

**Comment by muhummud** [comment]
Hello, My name is Muhammud Binhar (Mud). I'm Computer Engineering student at KMUTT. I would like to participate into this localization campaign due to my interest in Quantum field of knowledge and I want to encourage more Thai people to invest their interest with local language translation.

Email for contact: muhummud.bh@gmail.com

**Comment by Harlequinne007** [comment]
Hello Guys . My Name is Chatrphol Owanonchai (maybe you can call me Nine ). I'm studying at Traimudomsuksa school in Arts-Math Field. I'm interested in Quantum Computing , Classical Computing and Quantum Physics . I'd like to join this project cuz I think this project can help me better at translations and understand more about Qiskit. :D

Email for My contact : chatrphol.nine@gmail.com

**Comment by jiravatt** [comment]
Hi! I'm Jiravatt R. You can call me "Boom" which is my nickname. I taught Physics in high school form years. Now I'm looking for opportunity to contribute something to the Physics community. Hope I can contribute something here.

My email: jiravatt.r@gmail.com
Feel free to contact me!

**Comment by ksupasate** [comment]
Hello! I'm Supasate Vorathammathorn (Kom), a Computer Engineering student at KMUTT. I'm interested in contributing to the Quantum Computing community by providing translations in the local language. 

Contact Email: ksupasate@gmail.com
