### ISSUE TITLE
Request for Arabic

### ISSUE THREAD

**Issue by FiberAhmed** [qiskit-community/qiskit-translations#758]
### Summary

- The language that I'd like to request.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_

**Comment by Rayyan10** [comment]
Hi @FiberAhmed ! Hope you’re doing well.
I have opened an issue and requested for Arabic translation. If you are still interested in contributing please comment on [Request for ARABIC ](https://github.com/qiskit-community/qiskit-translations/issues/959) as we need more contributors.
Thank you!
