### ISSUE TITLE
Translation of textbook and community tutorials

### ISSUE THREAD

**Issue by spencerking** [qiskit-community/qiskit-translations#84]
Is there any interest or plan to work on translations for the community tutorials and the textbook?

I was unable to find any discussion about either of these, so I figured I would open an issue.

**Comment by SooluThomas** [comment]
Hi @spencerking, We are currently in the planning phase to begin translations for the textbook. We have already begun translating the tutorials in the documentation - https://qiskit.org/documentation/tutorials/circuits/index.html

**Comment by SooluThomas** [comment]
We now have the beta testing for textbook translations. Should be published for translations soon

**Comment by SooluThomas** [comment]
We now have enabled translations for the Qiskit Textbook. 🎉  Instructions to join/ add new language are [here](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md).
