### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by AlexAlper** [qiskit-community/qiskit-translations#9]
https://crowdin.com/project/qiskit-docs
I want to start translating into Russian
Can you add the Russian language?

**Comment by spencerking** [comment]
I'm already a French translator, but I'm happy to be a translation lead here if we're allowed to work on multiple languages.

**Comment by VasilyShcherbinin** [comment]
I am happy to be a translator or proof-reader.

**Comment by a-zasypalov** [comment]
Hello community! I would like to join translation team as a translator/proofreader. Also I can be a translation lead it could be possible. 
@ndv87 @VasilyShcherbinin @AlexAlper @spencerking let's make this step to add Russian to the Crowdin. Are you still interested in adding translation? Please, let us know about it here. Thank you!

**Comment by IvanMason801** [comment]
Hi, would like to join translation team as a translator/proofreader. If the opportunity still available.

**Comment by a-zasypalov** [comment]
@SooluThomas seems like we have at least 3 people, who interested in translation work. Maybe we can start?

**Comment by a-zasypalov** [comment]
What are requirements for being a translation lead? If @spencerking can't be a lead of 2 translation teams then I can take this role if you don't mind

**Comment by SooluThomas** [comment]
Hi @a-zasypalov, Please send an email Samanvay Sharma (samanvay.sharma1@ibm.com) and Yuri Kobayashi (yurik@jp.ibm.com) by email as [per the instruction](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language) to further proceed

**Comment by spencerking** [comment]
@a-zasypalov @SooluThomas Sorry, I just saw this. I'm not a translation lead of another language, but do work on another language. I'm happy to co-lead with @a-zasypalov if that's allowed.

**Comment by a-zasypalov** [comment]
@spencerking thank you! Can't wait to start work! 👍

**Comment by elenasuraeva** [comment]
Hi. I want to join the team.

**Comment by a-zasypalov** [comment]
@elenasuraeva thank you for your interest in contributing! Process of adding translation possibility is going well, so I think soon we will have an opportunity to start working on.

**Comment by starktech23** [comment]
Hi everyone and thanks again for your interest to form the Russian Language team for the Qiskit Localization Project! Given that we now have a good number of volunteers, let's have a brief discussion this coming Wednesday on June 16 to get to know the team as well as decide the roles and scope as part of the project. Please reach out to me at samanvay.sharma1@ibm.com so that I may extend the calendar invite to you. Thanks!

**Comment by SooluThomas** [comment]
[Russian](https://crowdin.com/project/qiskit-docs/ru#) has been added to Crowdin. Please follow the [steps in the README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the team! 🎉
