### ISSUE TITLE
Request for ARABIC

### ISSUE THREAD

**Issue by Rayyan10** [qiskit-community/qiskit-translations#959]
### Summary

- The language that I'd like to request is Arabic.
- I'd like to be a _Translation Lead/ Proofreader/ Translator_

**Comment by moustafa7zada** [comment]
i can contribute if there are more of us

**Comment by Rayyan10** [comment]
Hi Moustafa, thanks for your response. I guess we’ll need one more to start a new language.

Hope more people will be interested 

> i can contribute if there are more of us

**Comment by SooluThomas** [comment]
Hi, thanks for your interest to contribute! We've had a request for [Arabic translations](https://github.com/qiskit-community/qiskit-translations/issues/758) sometime back but no one responded. It might be a good idea to reach out to the person who created the issue to see if they are still interested. Hope this helps.

**Comment by FiberAhmed** [comment]
I can contribute

**Comment by SooluThomas** [comment]
Thank you all for your interest to contribute!! ✨ Just to let you all know, we had updated the [acceptance criteria for adding a new language](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#what-is-the-criteria-for-adding-a-new-language). Please keep a note of that. 
> 1. A minimum of **five contributors** is necessary for any new languages to be added and receive official support from the administrators of the localization project.
> 2. One of the contributors in that language must be a Qiskit Advocate and should actively participate.
> 3. In addition to translators, we will need dedicated proof-readers to review the translations and approve accuracy of content in that language and to ensure that the translations can be released in that language.
> 4. Among the group of contributors, a translation lead must be identified to serve as a liaison with the administrators of the localization project. The lead must contact [Soolu Thomas](mailto:soolu.thomas@ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) and [Yuri Kobayashi](mailto:yurik@jp.ibm.com?subject=%5BGitHub%5D%20Qiskit%20Documentation%20Translation) by email containing the issue number (or link) and, a little intro about the TL(s) and the team after the above three criteria are met. 
> 5. The project administrators will schedule a meeting with the translation lead(s) of the proposed language. Please note that satisfying the minimum number of translators does not automatically make the language ready to be added to Crowdin. It will be very important for the team to make continuous progress and to be active.

**Comment by Ihssene-Brahimi** [comment]
Hi there, I'd love to work on this!

**Comment by 0sophy1** [comment]
Hi @moustafa7zada @Rayyan10 @FiberAhmed @Ihssene-Brahimi ! We have more volunteers for this Arabic translation. Please contact to @Sophy at Qiskit slack! Thank you!

**Comment by imene-ouadah** [comment]
Hi, I want to contribute as a translator.

**Comment by moustafa7zada** [comment]
> Hi, I want to contribute as a translator. 

Here is a link to the server of the arabic localization team:
https://discord.gg/JkHdmwHW
Wlc aboard

**Comment by moustafa7zada** [comment]
> Hi, I want to contribute as a translator. 

Here is a link to the server of the arabic localization team:
https://discord.gg/JkHdmwHW
Wlc aboard

**Comment by 0sophy1** [comment]
Hi @moustafa7zada ! How things going with Arabic team formation? please ping to @Sophy at the Qiskit Slack for sync.

**Comment by SooluThomas** [comment]
Hi @moustafa7zada @Rayyan10 @FiberAhmed @Ihssene-Brahimi @imene-ouadah @Ihssene-Brahimi, due to lack of activity, I'm closing this issue. Please feel free to reopen whenever. 

I also wanted to let you know that we have [paused adding new languages to Crowdin](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate) until further notice. This is due to quite a few expected changes that is upcoming in the documentation.
