### ISSUE TITLE
Request for Sinhala

### ISSUE THREAD

**Issue by SuhiG** [qiskit-community/qiskit-translations#978]
### Summary

- I'm looking for fluent "Sinhala" speakers to translate Qiskit Notebooks.
- I will be taking the role of Translation Lead.
- A new language addition requires both a Translator and a Proofreader, so I am seeking at least 3 individuals (2 or more Translators and 1 or more Proofreaders).
- I would like to invite all interested parties.
- Please feel free to contact me on the Qiskit Slack channel as well. [Name: Sudeera Gunathilaka]

**Comment by SooluThomas** [comment]
Hi! Thanks for your interest to contribute. We have a set of acceptance criteria that has to be fulfilled before a language can be added to Crowdin. The first criteria being to have a minimum of 5 volunteers. Let us use this issue to recruit more volunteers who are interested in doing Czech translations.

For more info, please refer to ["How to add a new language to translate?" section in README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate).
